-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.33 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for project_pfe
DROP DATABASE IF EXISTS `project_pfe`;
CREATE DATABASE IF NOT EXISTS `project_pfe` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;
USE `project_pfe`;

-- Dumping structure for table project_pfe.categories
DROP TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table project_pfe.categories: ~4 rows (approximately)
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` (`id`, `name`, `image`) VALUES
	(1, 'devolepement & Programation', 'development.jpg'),
	(2, 'design', 'designing.jpeg'),
	(4, 'Montage', 'montage.jpeg'),
	(6, 'e-commerce', 'E-commer.jpeg');
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;

-- Dumping structure for table project_pfe.products
DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `text` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `image_pro` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `prix` float NOT NULL,
  `id_user` int(11) NOT NULL,
  `id_categori` int(11) NOT NULL,
  `evaluation` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'Good Seller',
  `Responsing` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '1 Hour',
  `Buyers` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '124',
  PRIMARY KEY (`id`),
  KEY `id` (`id`),
  KEY `FK__users` (`id_user`),
  KEY `FK__categories` (`id_categori`),
  CONSTRAINT `FK__categories` FOREIGN KEY (`id_categori`) REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK__users` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table project_pfe.products: ~42 rows (approximately)
/*!40000 ALTER TABLE `products` DISABLE KEYS */;
INSERT INTO `products` (`id`, `description`, `text`, `image_pro`, `prix`, `id_user`, `id_categori`, `evaluation`, `Responsing`, `Buyers`) VALUES
	(28, 'Je peux construire une application iOS complÃ¨te ou modifier n\'importe quelle application, pour 5 $ pour 5 interfaces, en utilisant le langage Swift sur le programme XCODE, que ce soit API ou Firebase, pendant le temps spÃ©cifiÃ© par le client et selon ce qui convient Ã  l\'application', 'CrÃ©er une application iOS Ã  partir de zÃ©ro', 'web.jpg', 140, 5, 1, 'Good Seller', '1 Hour', '124'),
	(29, 'Paix, la misÃ©ricorde et les bÃ©nÃ©dictions de Dieu\r\nje vous prÃ©sente\r\nConcevoir professionnellement des sites Web et des applications Web dans les derniers langages de programmation, avec un design moderne et crÃ©atif\r\nCompatible avec tous les Ã©crans de tÃ©lÃ©phone. Tablette et ordinateur\r\nLaravel, html5, css3, jQuery, javascript, PHP, Bootstrap...\r\nMySQL, MS SQL Server, Oracle...\r\nTout ce dont vous avez besoin, je peux programmer et concevoir pour rÃ©pondre Ã  vos besoins\r\nConception de sites Web Ã  partir de zÃ©ro.\r\n- Modifier des sites Web et des applications prÃªts Ã  l\'emploi et rÃ©soudre leurs problÃ¨mes.\r\nLes meilleurs rapports.\r\nHeureux d\'aider les Ã©tudiants dans leurs projets de fin d\'Ã©tudes avec l\'explication des codes\r\nAccepter de remettre le code source\r\n\r\n**Je vous prÃ©sente**\r\n- Une page qui comprend la programmation et la conception\r\nou alors\r\nUn rapport, y compris la programmation et la conception', 'Conception et programmation de sites Web PHP MySQL', 'a4d668117f61ac3aa4a300f43c684390.png', 123, 8, 1, 'Good Seller', '1 Hour', '124'),
	(30, 'GrÃ¢ce Ã  ce service, je peux concevoir et coder ma page Web en utilisant la technologie C# et C# (ASP.NET & C#). Je peux Ã©galement le lier Ã  des bases de donnÃ©es Ã  la demande telles que SQL Server, ORACLE, MYSQL et autres.', 'Concevoir deux pages Web en utilisant (ASP.NET) ', '284b1107cf5cbdc751f12df143d56d5e.jpg', 1266, 7, 1, 'Good Seller', '1 Hour', '124'),
	(31, 'Que la paix soit sur toi, mon cher frÃ¨re\r\nNous sommes heureux de fournir nos services professionnels Ã  nos prÃ©cieux clients qui font confiance Ã  nos services et nous nous efforcerons d\'Ãªtre Ã  leur meilleur (si Dieu le veut)\r\nDans ce service, nous construirons des sites complets comme le client le souhaite, avec une programmation spÃ©ciale Ã  partir de zÃ©ro sans modÃ¨les prÃªts Ã  l\'emploi en php et base de donnÃ©es MySql avec les derniÃ¨res versions disponibles\r\nLe site sera dynamique et personnalisÃ© selon les souhaits du client\r\nNous concevons diffÃ©rents types de sites Web (blogs, boutiques en ligne, publicitÃ©s, etc...)\r\nNous allons programmer une page pour 5 $ ou modifier le code ou concevoir une page initiale pour le site et le coÃ»t final du projet sera dÃ©terminÃ© aprÃ¨s accord sur les dÃ©tails\r\n** Veuillez me contacter pour plus d\'informations **\r\nVeuillez consulter les mises Ã  jour pour voir plus de fonctionnalitÃ©s dans le service', 'Programmation de sites php et mysql et javascript       ', 'web.jpg', 4000, 9, 1, 'Good Seller', '1 Hour', '124'),
	(32, 'Cher client,\r\nVous avez un projet et avez besoin d\'une application Android et/ou iOS professionnelle avec une livraison rapide ?\r\nVous souhaitez gagner de l\'argent grÃ¢ce aux publicitÃ©s Google ou Facebook ou autres ?\r\nNe cherchez plus, vous Ãªtes au bon endroit.\r\n\r\nJe dÃ©veloppe une page d\'une page (statique) et je la livre en une seule journÃ©e avec Splash Screen en cadeau.\r\n\r\nJ\'ai une expÃ©rience pratique dans le domaine du dÃ©veloppement d\'applications Android et iOS qui me permettent de fournir de nombreuses fonctionnalitÃ©s intÃ©ressantes pour votre application,\r\n\r\n1- CrÃ©ez une application complÃ¨te qui fonctionne Ã  la fois sur les systÃ¨mes Android et iOS\r\n2- L\'application est compatible avec toutes les tailles d\'Ã©cran de tÃ©lÃ©phone\r\n3- DÃ©veloppement et construction UI/UX\r\n4- Transformer une conception UI/UX en une application complÃ¨te\r\n5- Application professionnelle et rapide avec de hautes performances\r\n6- Application multilingue\r\n7- Ajouter une animation\r\n8- Connectez l\'application Ã  l\'API et Ã  la base de donnÃ©es\r\n9- IntÃ©gration de l\'application avec les dÃ©tecteurs du tÃ©lÃ©phone (appareil photo, GPS....)\r\n\r\nEt bien d\'autres fonctionnalitÃ©s', 'CrÃ©er une application professionnelle pour Android et iPhone', 'f24323ab709bfb5422de50d5eb4ae039.jpg', 4400, 6, 1, 'Good Seller', '1 Hour', '124'),
	(33, 'Programmation PHP : script simple ou complet ou application web,\r\ndÃ©pend de votre commande,\r\nAvec l\'ajout de toutes les fonctionnalitÃ©s que vous souhaitez.\r\n\r\n== Le prix d\'un service (5$) Ã©quivaut Ã  une page ==\r\n\r\nSi l\'application Web utiliseraÂ : -\r\n-HTML/HTML5\r\n-CSS/CSS3\r\n- JavaScript\r\njQuery\r\n- Amorcer\r\n- Vue.Js (sur votre demande)\r\n\r\n(prix et durÃ©e varient selon votre demande)\r\n((Veuillez noter que ce service ne fournit pas de design professionnel, il ne propose qu\'un design simple ou si un script que vous avez fait prÃ©cÃ©demment qui contient un design ou un design selon votre demande <un budget spÃ©cial pour le design que vous souhaitez>) )', 'Script PHP/Programmation d\'applications Web', '4d8b85326a6cd91d750a00cbf2bbd759.jpg', 5222, 4, 1, 'Good Seller', '1 Hour', '124'),
	(35, 'Conception et programmation d\'applications informatiquesJe conÃ§ois et programme tout programme pour votre ordinateur personnel (pour Windows) selon votre demande\r\nQu\'il s\'agisse d\'un programme de service, d\'un programme d\'archivage, d\'un programme comptable ou de tout autre type\r\n\r\nUtilisation des technologies .NET. Avec les fonctionnalitÃ©s suivantes :\r\nInterfaces et modÃ¨les distinctifs.\r\n- Assistant pour imprimer des rapports Ã  la demande.\r\n- Un systÃ¨me de sauvegarde au cas oÃ¹ le programme traite des bases de donnÃ©es.\r\n\r\nJe conÃ§ois et programme une interface d\'application unique avec trois zones de saisie et la relie Ã  une base de donnÃ©es si vous le souhaitez\r\n\r\nLien vers mon profil (Ã  propos de mon travail)Â :\r\nhttps://fuad.work/CV\r\n\r\nGalerie indÃ©pendante de mon travail :\r\nhttps://mostaql.com/u/Fuad_Sale7/portfolio', 'Conception et programmation d\'applications informatiques', 'b1efd4ce8a49873e75bb391e67bf3b26.jpg', 5990, 14, 1, 'Good Seller', '1 Hour', '124'),
	(36, 'Si vous avez un projet et que vous souhaitez crÃ©er une base de donnÃ©es dÃ©taillÃ©e et claire en fonction de votre demande, je peux le faire de maniÃ¨re correcte et comprÃ©hensible.J\'ai crÃ©Ã© de nombreuses bases de donnÃ©es pour divers projets Ã  l\'aide de SQL SERVER. Je ferai 4 tables pour ce service\r\nS\'il y a des modifications Ã  cette rÃ¨gle, je la modifierai Ã  votre satisfaction, cher client', 'CrÃ©er une base de donnÃ©es Ã  l\'aide du serveur SQL', 'ade93a3f46fb0fd0e186b0ead9a503da.jpg', 1230, 3, 1, 'Good Seller', '1 Hour', '124'),
	(37, 'Bonjour\r\nJe vous propose un service de programmation de bases de donnÃ©es sous Oracle (Oracle DataBase).\r\nVersions utilisÃ©es 10g et plus.\r\nPlus de 10 ans d\'expÃ©rience dans ce domaine continue Ã  ce jour.\r\n\r\nLa base de donnÃ©es comprendÂ : -\r\n. les tables\r\n. Vues\r\n. ProcÃ©dures\r\n. Paquets\r\n. DÃ©clencheurs\r\n. Les fonctions\r\n. Et d\'autres\r\n\r\n. Le dÃ©lai de livraison dÃ©pend du volume de travail.\r\n. Le tableau est complet avec toutes les restrictions pour seulement 5 $.\r\n(ProcÃ©dures, Packages, DÃ©clencheurs, Fonctions) Ã  convenir avec le client.\r\n\r\n. Assistance technique aprÃ¨s livraison.\r\n. PrÃ©parez-vous Ã  toute modification aprÃ¨s remise de la base de donnÃ©es.\r\n\r\nindÃ©pendant\r\nhttps://mostaql.com/u/MHejazy\r\n\r\nLa satisfaction du client est mon premier objectif.', 'Programmation de bases de donnÃ©es avec Oracle', '0def1a42f91ff03abc55bdf55c82e48c.jpg', 1200, 4, 1, 'Good Seller', '1 Hour', '124'),
	(38, 'J\'ajouterai rÃ©guliÃ¨rement des annonces Admob au sein d\'un projet et avec les meilleures performances possibles\r\nVous bÃ©nÃ©ficierez de chaque annonce qui apparaÃ®t dans votre application/jeu\r\n\r\nTypes d\'annonces que je vais vous ajouterÂ :\r\n1- BanniÃ¨re (c\'est la publicitÃ© qui a une taille spÃ©cifique et qui apparaÃ®t avec l\'utilisation de l\'application/du jeu)\r\n2- Interstitiel (c\'est la publicitÃ© qui apparaÃ®t Ã  l\'utilisateur lorsqu\'il navigue entre les scÃ¨nes ou lorsqu\'il gagne/perd, et vous pouvez l\'ignorer aprÃ¨s 5 secondes)\r\n3- RÃ©compensÃ© (il s\'agit d\'une publicitÃ© vidÃ©o de 30 secondes, aprÃ¨s quoi vous pouvez la sauter et oÃ¹ elle apparaÃ®tra, soit pour doubler les bÃ©nÃ©fices lorsque le rÃ´le est terminÃ©, soit pour gagner une gemme ou un prix)\r\n\r\nVous pouvez choisir les emplacements des annonces et les conditions d\'apparition, ou placer des annonces en fonction de mon expÃ©rience aprÃ¨s avoir prÃ©visualisÃ© le projet\r\n\r\nIl y aura 4 scripts autres que le sdk admob', 'Ajoutez des publicitÃ©s Admob Ã  votre jeu dans Unity', '7837dc97e2a836c6e983b3dabe0becdc.jpg', 1235, 9, 1, 'Good Seller', '1 Hour', '124'),
	(39, 'âˆŽ Si vous cherchez quelqu\'un pour :\r\n\r\nâ€¢ Convertir n\'importe quel design PSD | xd vers (page web professionnelle)\r\n\r\nâ€¢ Concevez un site Web complet Ã  partir de zÃ©ro ou concevez une page de destination professionnelle, alors vous Ãªtes au bon endroit\r\n\r\nâˆŽ FonctionnalitÃ©s des servicesÂ :\r\n\r\nâ€¢ Conception d\'une seule page\r\n\r\nâ€¢ Conception cohÃ©rente et rÃ©active avec toutes les tailles d\'Ã©cran et tous les appareils.\r\n\r\nâ€¢ Codes propres et bien rangÃ©s qui rÃ©pondent aux normes de convivialitÃ© des moteurs de recherche.\r\n\r\nâ€¢ Ajout d\'animation au site.\r\n\r\nâ€¢ (J\'implÃ©menterai toute modification gratuitement si vous souhaitez modifier une chose simple aprÃ¨s l\'achat du service)\r\n\r\nâˆŽ CompÃ©tences que j\'utilise :\r\n\r\nâ€¢ Pug Js | HTML5\r\n\r\nâ€¢ CSS3 | TOUPET\r\n\r\nâ€¢ AmorÃ§age4\r\n\r\nâ€¢ Javascript/Jquery\r\n\r\nâ€¢ Gestionnaire de tÃ¢ches (Webpack)', 'Conception de pages de destination professionnelles', 'f71aeebd8188faee3b44c9e9a0f2f957.jpg', 2001, 8, 1, 'Good Seller', '1 Hour', '124'),
	(40, 'Il est trÃ¨s facile de nos jours d\'aller sur Google et de tÃ©lÃ©charger une page de destination gratuite et de la lier Ã  un domaine, puis de la tÃ©lÃ©charger sur un hÃ©bergement, mais cela garantira-t-il le succÃ¨s de votre campagne marketingÂ ? Cela rendra-t-il les visiteurs de la page convaincus de votre produitÂ ? Cela incitera-t-il les visiteurs Ã  acheterÂ ?\r\nLa rÃ©ponse est dÃ©finitivement non. Parce que la page de destination n\'est qu\'un moyen, mais la fin est le marketing. Vous n\'avez pas seulement besoin d\'un site Web, vous avez besoin d\'une stratÃ©gie.\r\nJe vais non seulement concevoir une page de destination normale pour vous, mais je vais concevoir une page de destination efficace qui exprime avec brio l\'idÃ©e de votre produit, ce que je conÃ§ois pour vous estÂ :\r\nâ€¢ Une landing page avec un message persuasif pour motiver les visiteurs Ã  acheter votre produit.\r\nâ€¢ Une landing page Ã©lÃ©gante et attrayante qui donnera de la crÃ©dibilitÃ© Ã  votre entreprise.\r\nâ€¢ Une landing page contenant toutes les informations et rÃ©ponses aux questions que peuvent se poser vos clients.\r\nâ€¢ Une landing page parfaitement archivÃ©e pour apparaÃ®tre dans les premiÃ¨res positions des moteurs de recherche.\r\nâ€¢ Une page de destination qui contient un logiciel spÃ©cial pour rÃ©cupÃ©rer toutes les donnÃ©es et informations dont vous avez besoin sur les visiteurs de la page afin d\'amÃ©liorer votre campagne de marketing.\r\n* La premiÃ¨re conception commence par 3 sections et est rÃ©active', 'Programmation et conception d\'une landing page ', '520b4221a2dd213aaf8286b75826da85.jpg', 1356, 7, 1, 'Good Seller', '1 Hour', '124'),
	(41, 'Bienvenue..\r\nJe suis l\'architecte Orwa Qassem... mon service est :\r\n_ Conception architecturale extÃ©rieure tridimensionnelle de diverses configurations architecturales (maisons_villas_bÃ¢timents_cafÃ©s_bÃ¢timents administratifs) et fournissant un travail prÃ©cis et professionnel.\r\n_ Design d\'intÃ©rieur (dÃ©coration) pour diffÃ©rents espaces architecturaux.\r\nConception 3D de parcs et sites publics (paysage)\r\n\r\nUtilisation de 3ds Max avec optimisation et affichage de la meilleure qualitÃ© de travail Ã  l\'aide de Photoshop pour obtenir les meilleurs rÃ©sultats.\r\nTarif des prestations :\r\nPour l\'amÃ©nagement extÃ©rieur : 5 $ par 3 mÃ¨tres carrÃ©s\r\nPour la dÃ©coration : 5 $ par 3 mÃ¨tres carrÃ©s\r\nPour les sites publics : 5 $ par 10 mÃ¨tres carrÃ©s\r\n\r\nLa possibilitÃ© de modification est illimitÃ©e jusqu\'Ã  ce que le travail soit entiÃ¨rement satisfait', 'Conception d\'architecture 3D avec 3ds max', '85cb3fe96211e041ce407e970685b154.jpg', 1000, 3, 2, 'Good Seller', '1 Hour', '124'),
	(42, 'Architecte avec une grande expÃ©rience, je dessine des plans - faÃ§ades et sections architecturales dans AutoCAD avec une grande prÃ©cision et de maniÃ¨re professionnelle.Les dessins peuvent Ã©galement Ãªtre modifiÃ©s d\'AutoCAD Ã  Photoshop et de PDF Ã  AutoCAD. Je suis rapide dans mes transactions\r\nEt livraison au format PDF et fichier AutoCAD pour une impression facile de haute qualitÃ©.\r\nJe peux Ã©galement livrer des fichiers au format jpeg -psd\r\nPour 5 $, vous obtiendrez un dessin technique de 100 mÃ¨tres carrÃ©s', 'Architecte de grande expÃ©rience, je dessine des plans - faÃ§ades', 'be7cd1ccfd4f299c31ca2ed4ad234214.jpg', 2902, 4, 2, 'Good Seller', '1 Hour', '124'),
	(43, 'Le travail est fait avec professionnalisme et qualitÃ©\r\nEt je vous garantis que votre stand remplira sa fonction prÃ©vue\r\nC\'est pour 5 $ par mÃ¨tre carrÃ© d\'espace de stand\r\ntu auras\r\n* 6 images en perspective du stand avec une grande prÃ©cision et un grand rÃ©alisme avec toutes les sorties, l\'Ã©clairage et les personnes, et tout cela pour chaque mÃ¨tre carrÃ© d\'espace de stand\r\n* Un fichier exÃ©cutable AutoCAD pour mettre en Å“uvre la conception sur la rÃ©alitÃ©, montrant toutes les dimensions de la cabine\r\nEt tout Ã§a pour chaque mÃ¨tre carrÃ©\r\n- Je ferai deux modifications pour vous en Ã©change de cela, et si vous avez besoin d\'autres modifications, consultez les amÃ©liorations du service\r\nLe service sera mis en Å“uvre et livrÃ© deux jours aprÃ¨s la demande de service\r\nJe suis honorÃ© de traiter avec tout le monde', 'Conception de stand - exposition - stand - stand - stands', '0e6c263d8e113d4c07e5b4b89918d266.jpg', 342, 6, 2, 'Good Seller', '1 Hour', '124'),
	(44, 'Bienvenue\r\nJe m\'appelle Islam, graphiste.\r\nJ\'ai plus de deux ans d\'expÃ©rience dans ce domaine et je suis donc parti en freelance\r\n# Si vous avez besoin d\'un logo professionnel, une nouvelle idÃ©e pour votre domaine\r\nNe vous inquiÃ©tez pas, vous Ãªtes au bon endroit\r\n\r\nJ\'espÃ¨re que vous visiterez ma galerie\r\nhttps://mostaql.com/dashboard/portfolio\r\n\r\n## mes expÃ©riences ##\r\nJe travaille sur les programmes de conception suivants :\r\n- Adobe Illustrator\r\n- Adobe Photoshop\r\nJe n\'offre ce service qu\'une seule crÃ©ation de logo.\r\nCe que vous obtiendrez pour ce service\r\nUn nombre infini de modifications jusqu\'Ã  ce que vous soyez satisfait du design final\r\nConceptions uniques et de haute qualitÃ© avec une garantie de non imitation ou copie\r\n- Copie au format PDF\r\n- Copie JPEG\r\n\r\n* Si vous avez besoin d\'une conception dans les plus brefs dÃ©lais, vous pouvez voir les dÃ©veloppements au cas oÃ¹ vous souhaiteriez acheter des fonctionnalitÃ©s supplÃ©mentaires\r\nMerci', 'Conception graphique de logos et de marques.', '96d5b2ab8d07553f210dae84b3aa7a9c.jpg', 1324, 7, 2, 'Good Seller', '1 Hour', '124'),
	(45, 'L\'idÃ©e d\'entreprise est bien dÃ©crite Ã  travers le logo crÃ©atif et votre sociÃ©tÃ© commerciale ou tout projet sur lequel vous travaillez, comme la construction, la mÃ©decine ou mÃªme un animal signifie un vÃ©tÃ©rinaire. Je vais vous aider en crÃ©ant un superbe ensemble de logos crÃ©atifs qui s\'accordent parfaitement avec votre travail. Je concevrai pour vous une suite commerciale complÃ¨te qui aidera votre entreprise Ã  se dÃ©marquer.\r\n\r\nVeuillez lire la description avant de commander le service\r\n\r\nQu\'obtiendrez-vous ?\r\nUne idÃ©e de conception de logo\r\nUne seule conception de modÃ¨le\r\nModifier une fois\r\ncouleur noire\r\nLa livraison est un fichier 150*150 pixels au format png\r\n\r\nJ\'aime tellement mon travail que je le maÃ®trise, Dieu soit louÃ©.\r\nVous pouvez Ã©galement soumettre une demande uniquement aprÃ¨s avoir dÃ©cidÃ© que vous aimez le service, Bonjour et Bienvenue, et s\'il n\'est pas approuvÃ©, vous Ãªtes le bienvenu.\r\nJ\'espÃ¨re de tout mon coeur que vous me contacterez.\r\n\r\nMerci Ã  vous', 'Je vais concevoir un logo crÃ©atif pour votre entreprise', '3adb00c36709e79686b09a80c296cd41.jpg', 4000, 8, 2, 'Good Seller', '1 Hour', '124'),
	(46, 'Bienvenue\r\n- Je concevrai un logo en fonction du type de domaine dans lequel vous vous spÃ©cialisez (commerce, privÃ©,\r\nindustrie, pharmacie, entreprise)\r\nSoumettez un formulaire pour le logo requis\r\nLa conception est de haute qualitÃ©, des normes professionnelles et une grande prÃ©cision dans la livraison\r\n(cohÃ©rence des couleurs, respect de la taille des polices d\'Ã©criture)\r\nRespectez les espaces entre les Ã©lÃ©ments de conception.\r\nL\'idÃ©e du design est distincte et diffÃ©rente du reste des logos et n\'est pas imitÃ©e.\r\nLes fichiers livrÃ©s sont au format jpg png pdf\r\nJ\'espÃ¨re de tout mon coeur que vous me contacterez.', 'Conception de logo innovante et crÃ©ative uniquement', '93978a86a4094a46a994fa9e90a12545.jpg', 700, 9, 2, 'Good Seller', '1 Hour', '124'),
	(47, 'Bonjour\r\nBonjour Ã  tous, merci\r\n\r\n- Concevoir un logo professionnel (modÃ¨le 1) Ã  la demande avec une idÃ©e innovante et belle.\r\n\r\nLe logo est livrÃ© avec un fond transparent aux formats PNG et JPG, et une alliance blanche de trÃ¨s haute qualitÃ©.\r\n\r\nVous avez le droit de modifier 3 fois sur le mÃªme formulaire.\r\n\r\n* Pour les modÃ¨les Ã  3 logos, vous trouverez leur propre dÃ©veloppement dans les mises Ã  jour.\r\n\r\n* Pour obtenir les fichiers source complets du logo PSD-Ai-PDF, vous pouvez choisir le dÃ©veloppement appropriÃ© ci-dessous.\r\n\r\nRemarque : toutes les Å“uvres d\'art sont ma propre conception', 'Conception de logo professionnel avec des spÃ©cifications Ã©levÃ©es', 'ad4c3256671db54fd86fd1a1baa95239.jpg', 236, 14, 2, 'Good Seller', '1 Hour', '124'),
	(48, 'Paix, la misÃ©ricorde et les bÃ©nÃ©dictions de Dieu\r\n\r\nDans ce service, je ferai une conception complÃ¨te de l\'exposition, en partant de la conception jusqu\'au spectacle 3D\r\n\r\nJe vous fournirai une conception complÃ¨te comprenant des dessins d\'architecture, des dessins de distribution d\'Ã©clairage, des dessins de finition et des matÃ©riaux utilisÃ©s.\r\n\r\nJe vous fournirai un design comprenant toutes les dÃ©corations et logos de l\'exposition\r\n\r\nJe vous fournirai des idÃ©es nouvelles et non citÃ©es et chaque conception a le droit de propriÃ©tÃ©\r\n\r\nJe vous remettrai les fichiers source pour Autocad-3dsmax\r\n\r\nLe prix du service est de 5 $ par mÃ¨tre carrÃ©\r\n\r\nQue Dieu bÃ©nisse et aide', 'Conception d\'exposition ou de stand pour les grandes expositions', '345e4e5f289f38c0602d03d3fde1a342.jpg', 200, 15, 2, 'Good Seller', '1 Hour', '124'),
	(49, 'Je suis Reham, graphiste et artiste plasticien, je mÃªle l\'art au design pour obtenir un profil professionnel distinctif, innovant et Ã©lÃ©gant, adaptÃ© au domaine de votre entreprise.\r\nLaissez-moi faire et je vous Ã©tonnerai avec les rÃ©sultats, j\'ai plus de 6 ans d\'expÃ©rience dans le design et une expÃ©rience exceptionnelle dans la conception des profils d\'entreprises professionnelles distinguÃ©es, ce qui m\'assure de choisir les images haut de gamme appropriÃ©es pour votre entreprise et coordonnez-les avec le reste des Ã©lÃ©ments avec le savoir-faire d\'un designer de grand goÃ»t.\r\n\r\nCe que je vous offre pour le prix du service de baseÂ :\r\nConcevez une page unique du profil de votre entreprise de maniÃ¨re professionnelle et moderne.\r\n- Je fournirai le design sous la forme d\'une image de qualitÃ© appropriÃ©e pour l\'affichage.\r\n- Je modifierai les dessins (le cas Ã©chÃ©ant) jusqu\'Ã  ce que vous soyez satisfait.\r\n- Je choisirai les couleurs du design qui correspondent Ã  l\'identitÃ© visuelle de votre entreprise.', 'Conception de profil professionnel pour votre entreprise', '570f37655a21dd2436d3c8b9d737c258.jpg', 1200, 15, 2, 'Good Seller', '1 Hour', '124'),
	(50, 'Je vous offre, cher client, pour le prix principal de la prestation\r\n1_un Ã©chantillon de votre logo\r\n2_Livraison en formats (jpg_png)\r\nUne image normale et une image vierge\r\n3_ L\'Ã©dition est disponible une fois\r\n4_ Soumettez le logo dans une taille de 300 x 300 pixels\r\nservice professionnel\r\n1_ Deux modÃ¨les aux idÃ©es diffÃ©rentes\r\n2_ Le formulaire approuvÃ© doit Ãªtre soumis dans les formats suivants\r\n(jpg_png_pdf)\r\n3_ La modification se fait 3 fois gratuitement sur un modÃ¨le\r\n\r\nPour demander le fichier ouvert du logo ou demander un manuscrit en arabe, vous pouvez consulter les Ã©volutions du service', 'CrÃ©ation de logo - logo professionnel en adobe xd', '854ae541ec558dd56ae173629a3f9671.jpg', 2000, 15, 2, 'Good Seller', '1 Hour', '124'),
	(51, 'Dans ce service, je mettrai en Å“uvre le design que vous souhaitez\r\nPour Snapchat, Instagram, Facebook ou autres sÃ©parÃ©ment\r\nTailles d\'affiche ou d\'histoire, ou selon votre dÃ©sir et prÃ©fÃ©rence.\r\n\r\nVous recevrez le design en haute qualitÃ© sous forme d\'image prÃªte Ã  Ãªtre publiÃ©e sur les sites de rÃ©seaux sociaux au format Jpg ou png\r\nLe design exprimera vos aspirations\r\nIl fournira l\'image correcte que vous voulez que vos clients et clients voient\r\nVotre produit ou service sera prÃ©sentÃ© de maniÃ¨re attrayante, Ã©lÃ©gante et cohÃ©rente avec votre vision de marque\r\nCe qui renforce la notoriÃ©tÃ© de votre activitÃ© et contribue Ã  augmenter les ventes, si Dieu le veut.\r\n\r\nJ\'ai plus de 7 ans d\'expÃ©rience dans la conception, l\'Ã©dition et la retouche\r\nIl dÃ©tient plusieurs certificats dans le domaine, notamment du California Institute of the Arts\r\n\r\nJe serai prÃªt et coopÃ©ratif pour un certain nombre de modifications non drastiques.\r\nDÃ©lai de livraison : deux jours et peut varier d\'un design Ã  l\'autre\r\ncoÃ»t par conception\r\nAvec la possibilitÃ© d\'augmenter le coÃ»t de conceptions trÃ¨s distinctives\r\nEt je sais que nous ne serons pas en dÃ©saccord, si Dieu le veut :)\r\nIl y a une remise parmi les dÃ©veloppements, n\'oubliez pas de la vÃ©rifier ^_^', 'Conception publicitaire distinguÃ©e pour les mÃ©dias sociaux, ', '93a6c587d4b3b7811717327d3b4d3608.png', 1230, 4, 2, 'Good Seller', '1 Hour', '124'),
	(52, 'Paix, la misÃ©ricorde et les bÃ©nÃ©dictions de Dieu\r\nBienvenue dans mon monde\r\n\r\nJe suis trÃ¨s heureux de vous rendre service..\r\nJe suis Fawaz, ingÃ©nieur et graphiste\r\n\r\nJ\'ai fait des designs crÃ©atifs un monde pour moi\r\n* Les normes internationales me fixent des limites\r\n* J\'ai une grande imagination et un sens artistique Ã©levÃ©\r\n* Je travaille avec passion afin d\'Ã©lever mes clients pour qu\'ils soient partenaires de leurs succÃ¨s..\r\n\r\nJ\'ai une grande expÃ©rience dans ce domaine et je progresse Ã  un rythme rÃ©gulier et distinct et j\'amÃ©liore le design pour Ãªtre le meilleur\r\nJe vous fournirai un design professionnel et attrayant dans le domaine que vous souhaitez.\r\nVous pouvez consulter mon portfolio :\r\nhttps://mostaql.com/u/Fawaz_Baker/portfolio\r\nEnvoyez-moi simplement les dÃ©tails de la conception (service)\r\nâ–º Le service pour une conception professionnelle gÃ©nÃ©rale pour toute plateforme (Facebook - Twitter - Instagram - ....)\r\nâ–ºLivraison de 1 dessin\r\nâ–ºEn png - jpeg - EPS - PSD - AI - Id\r\nâ–º 1 modification jusqu\'Ã  ce que vous soyez 100% satisfait\r\nâ–ºLa conception est supÃ©rieure et la qualitÃ© de conception est de 600 x 600 pixels\r\nJ\'ai une trÃ¨s grande expÃ©rience dans le domaine de la conception graphique.Je vais concevoir tout ce que vous voulez pour votre projet Ã  partir de banniÃ¨res, mÃ©dias sociaux, flyers, couvertures de livres, invitations et bien d\'autres...\r\nMon objectif est de vous offrir le meilleur...', 'Beau design professionnel (brochure / couverture de livre / flyer / banniÃ¨re)', 'f40d03e7bae12c841edae95946e42962.jpg', 1200, 8, 2, 'Good Seller', '1 Hour', '124'),
	(53, '- Soyez sÃ»r que vous obtiendrez une vidÃ©o animÃ©e trÃ¨s professionnelle, pas moins que les vidÃ©os de la galerie professionnelle\r\n\r\nSoyez sÃ»r que vous obtiendrez la meilleure qualitÃ© au prix le plus bas.\r\n\r\n- Je conÃ§ois des vidÃ©os professionnelles d\'animation publicitaire et promotionnelle pour des sites Web, des applications et des entreprises de toutes sortes\r\nEffets audio et visuels attrayants.\r\n\r\n- Aussi, vidÃ©os snapchat, Instagram et n\'importe quelle taille que vous voulez.\r\n\r\n- Si vous n\'avez pas de script, je peux vous l\'Ã©crire en cadeau.\r\n\r\n- Le service principal nous vous proposons une simple vidÃ©o de 4 secondes. Pour augmenter la durÃ©e (voir amÃ©liorations du service)\r\n\r\n- Un service de commentaires audio avec vidÃ©o est disponible (voir amÃ©liorations du service)\r\n\r\n- Livrer le fichier au format MP4 avec une qualitÃ© HD1080\r\n\r\n- Ne recevez pas si vous n\'Ãªtes pas satisfait du travail et de la modification jusqu\'Ã  ce que la vidÃ©o reÃ§oive votre satisfaction', 'VidÃ©o d\'animation graphique professionnelle', 'bdf37e84d29376cea3add91aeec33a63.jpg', 230, 15, 4, 'Good Seller', '1 Hour', '124'),
	(54, 'Bonjour et bienvenue\r\nJe concevrai pour vous une superbe vidÃ©o professionnelle et distinctive, que ce soit pour votre page Facebook, site web, chaÃ®ne YouTube, campagne publicitaire pour vos entreprises, promotion de votre entreprise, ou simplement un album photo sous forme de vidÃ©o documentant vos souvenirs, anniversaire, mariage, fÃªte de remise des diplÃ´mes... etc.\r\nLe prix du service comprend un montage de 60 secondes, un bon montage avec de bonnes transitions, et n\'inclut pas les publicitÃ©s. Si vous voulez des capacitÃ©s Ã©levÃ©es et luxueuses, veuillez consulter les dÃ©veloppements.\r\n* La durÃ©e des travaux pour un montage rÃ©gulier est d\'une journÃ©e (24 heures.) Pour un montage VIP, deux jours ou plus, selon le type de dÃ©veloppement.\r\n* Le travail n\'est pas livrÃ© sous une forme open source\r\n* QualitÃ© vidÃ©o 1080p (qualitÃ© supÃ©rieure, une lÃ©gÃ¨re marge est ajoutÃ©e)\r\n* Il est remarquable pour la qualitÃ© mentionnÃ©e dans les dÃ©veloppements, car cela a Ã  voir avec la qualitÃ© de l\'image et les outils utilisÃ©s dans After Effects pour complÃ©ter la vidÃ©o, plus le niveau est Ã©levÃ©, plus les outils sont utilisÃ©s pour ajouter plus d\'esthÃ©tique.\r\n\r\nSoyez sÃ»r que vous ne partirez que si vous Ãªtes entiÃ¨rement satisfait du service.', 'Production vidÃ©o professionnelle pour tous types de vidÃ©os', '2b562c940609b559ce1e4e04db5465e2.jpg', 120, 4, 4, 'Good Seller', '1 Hour', '124'),
	(55, 'La paix, la misÃ©ricorde et les bÃ©nÃ©dictions de Dieu.\r\n\r\nSi vous souhaitez obtenir une vidÃ©o d\'animation graphique professionnelle pour votre entreprise ou votre site Web, vous Ãªtes au bon endroit.\r\n\r\nNous vous proposons un service de conception de vidÃ©o motion graphic :\r\n\r\n- Avec des designs modernes.\r\n- Prise en compte de l\'identitÃ© visuelle de votre projet.\r\n- Testez les plus beaux designs de votre annonce pour attirer les clients.\r\n\r\nLorsque vous commandez le service, vous recevez :\r\n\r\n- VidÃ©o graphique animÃ©e professionnelle toutes les 3 secondes\r\n- VidÃ©o Full HD au format MP4.\r\n-En un jour\r\nRemarques :\r\n1- La vidÃ©o ne comprend pas de commentaire audio (peut Ãªtre demandÃ© aux dÃ©veloppements)\r\n2- VidÃ©o graphique animÃ©e professionnelle de 60 secondes (peut Ãªtre demandÃ©e auprÃ¨s des dÃ©veloppements)\r\n3-VidÃ©o graphique animÃ©e professionnelle de 30 secondes (peut Ãªtre demandÃ©e Ã  partir de l\'application', 'Conception vidÃ©o graphique animÃ©e professionnelle', '1b6a302d1815a85c92c3e1adcaab69d0.jpg', 123, 6, 4, 'Good Seller', '1 Hour', '124'),
	(56, 'Bienvenue\r\n\r\n* Nous vous proposons un service de montage vidÃ©o complet (pour YouTube et autres plateformes...)\r\n*qui comprend le dÃ©coupage et l\'installation de scÃ¨nes, l\'ajout d\'effets, l\'insertion de textes, la correction des couleurs et l\'ajout de transitions cinÃ©matiques....\r\n* Comme le prix du service est pour toutes les 7 minutes avec tous les ajouts susmentionnÃ©s\r\n* Sortez les vidÃ©os dans la qualitÃ© que vous voulez, HD, FULL HD\r\n* PossibilitÃ© d\'Ã©diter 2 fois\r\n* Recevez le service dans les 24 heures\r\n\r\nNotre service est trÃ¨s distinguÃ© avec des offres attractives\r\n\r\nVeuillez consulter les mises Ã  jour', 'Montage professionnel complet et distinctif pour vos vidÃ©os', '86ca4cf4d003be6c5c0136651261321c.jpg', 500, 7, 4, 'Good Seller', '1 Hour', '124'),
	(57, 'Montage commercial professionnel\r\nSites de rÃ©seautage d\'affaires / commerciaux / sociaux dans toutes les clairiÃ¨res ainsi que les clairiÃ¨res d\'histoires\r\nPhotos et vidÃ©os rÃ©alistes\r\nAdaptÃ© aux exigences de chaque client parce que je Â« mets en Å“uvre de grandes idÃ©es Â».\r\n\r\nIl est temps de s\'Ã©lever au-dessus de la concurrence.\r\n\r\nToutes les trois secondes (selon la quantitÃ© de travail nÃ©cessaire, il peut diminuer ou augmenter)\r\nComprenant des scÃ¨nes avec de vraies photographies libres de droits, des effets sonores et des transitions professionnelles, des graphismes de haut niveau, une Ã©criture artistique en graphisme 3D, etc...\r\nVous serez 100% professionnel\r\nVous recevrez 3 fois des modifications jusqu\'Ã  ce que nous atteignions le professionnel souhaitÃ©\r\n\r\nLa durÃ©e de la vidÃ©o commence Ã  partir de 3 secondes, et la longueur que vous souhaitez se trouvera dans les dÃ©veloppements\r\n* Vous obtiendrez une haute qualitÃ© et n\'importe quel format que vous voulez * Mp4, Full HD ou 4K\r\n* Commentaire audio distinguÃ© dans tous les dialectes (voix anti ou masculine).\r\n\r\nVeuillez consulter mon portfolio sur le lien suivant sur une plateforme indÃ©pendante\r\nhttps://mostaql.com/u/yassineprod\r\n\r\nMontage commercial professionnel qui travaille pour augmenter le taux de vos clients\r\nJe travaille avec tous les logiciels de montage', 'Montage commercial professionnel et artistique', 'cfeaa7e041d8d43c37ea24e1edd817ef (1).jpg', 3000, 7, 4, 'Good Seller', '1 Hour', '124'),
	(58, 'Je peux concevoir un graphique animÃ© et une vidÃ©o d\'animation pour afficher vos services ou produits sous la forme d\'une vidÃ©o attrayante pour le client\r\n\r\nIl est utilisÃ© dans le e-marketing et pour expliquer l\'utilisation de diffÃ©rents sites Web et programmes mobiles\r\n\r\nOÃ¹ j\'ai conÃ§u plusieurs Å“uvres pour des entreprises arabes et Ã©trangÃ¨res, vous pouvez parcourir mes Å“uvres\r\n\r\nLa qualitÃ© vidÃ©o est jusqu\'Ã  Full HD 1080 au format MP4\r\n\r\nLa durÃ©e de la vidÃ©o est de 3 secondes', 'VidÃ©o graphique animÃ©e toutes les 5 secondes', '9f4b9b4bbb6e4eb27ccd6b7b44f85004.jpg', 299, 8, 4, 'Good Seller', '1 Hour', '124'),
	(59, 'Bienvenue\r\nJe vais crÃ©er des animations via Google Maps ou Google Earth pour n\'importe quel endroit que vous voulez, vous pouvez l\'utiliser dans des Vlogs ou faire de la publicitÃ© pour l\'emplacement de votre entreprise, etc.\r\nJe chercherai l\'endroit que vous voulez sur Google Maps ou Google Earth et je le prendrai en photo et ensuite je ferai une vidÃ©o pour vous de cette faÃ§on\r\n3 secondes\r\nJe serai heureux de rÃ©pondre Ã  votre projet de maniÃ¨re professionnelle et crÃ©ative\r\nN\'hÃ©sitez pas Ã  communiquer avec moi\r\nSalutations Ã  vous', 'Je vais crÃ©er des cartes animÃ©es pour n\'importe quel endroit que vous voulez', 'ac0c11910bc3ae1693dbadcf25bf64b7.jpg', 400, 9, 4, 'Good Seller', '1 Hour', '124'),
	(60, 'Paix, la misÃ©ricorde et les bÃ©nÃ©dictions de Dieu\r\nJe vous propose un service de conception de vidÃ©os d\'animation graphique et de vidÃ©os d\'introduction pour les entreprises et les institutions avec les meilleures techniques de conception et de haute qualitÃ© pour obtenir une publicitÃ© trÃ¨s spÃ©ciale\r\nSpÃ©cification de service\r\nPour 5$ je vais vous prÃ©senter une vidÃ©o de 5 secondes\r\n* Ajouter des effets sonores et une musique de fond\r\n* QualitÃ© vidÃ©o Full HD 1080p au format MP4\r\n*Pour les autres demandes, veuillez consulter les dÃ©veloppements\r\n*Le prix n\'inclut pas le commentaire audio\r\nPour demander une voix off, veuillez d\'abord m\'envoyer un e-mail', 'Mises Ã  jour vidÃ©o des animations graphiques disponibles', 'f9be00a516b0c3e29d2453bd2788a733.jpg', 600, 14, 4, 'Good Seller', '1 Hour', '124'),
	(61, '- Assurez-vous que vous obtiendrez une vidÃ©o graphique animÃ©e de taille Snapchat trÃ¨s professionnelle, pas moins que les vidÃ©os de la galerie professionnelle.\r\n\r\nAu prix le plus bas, je crÃ©e une vidÃ©o toutes les 4 secondes pour 5 $\r\n\r\n- Je conÃ§ois des vidÃ©os professionnelles d\'animation publicitaire et promotionnelle pour des sites Web, des applications et des entreprises de toutes sortes\r\nEffets audio et visuels attrayants.\r\n\r\n- Et aussi la taille Instagram, pour deux tailles pour la mÃªme vidÃ©o voir les Ã©volutions..\r\n\r\n- Si vous n\'avez pas de script, je peux vous l\'Ã©crire en cadeau.\r\n\r\n- Il y a un commentaire audio professionnel (voir amÃ©liorations)\r\n\r\n- Livrer le fichier au format MP4 avec une qualitÃ© HD1080\r\n\r\nN\'abandonnez pas si vous n\'Ãªtes pas satisfait du travail', 'Taille snapchat de motion graphics professionnels au meilleur prix', '23c33ea0a45b2e851cc8386706dccbd1.jpg', 60, 15, 4, 'Good Seller', '1 Hour', '124'),
	(62, 'Concevez une vidÃ©o graphique animÃ©e professionnelle pour vos produits ou votre site Web. Pour augmenter vos ventes et briller dans votre entreprise\r\nQu\'est ce que tu obtiens\r\nLa vidÃ©o est en HD 720p pour une meilleure qualitÃ©, voir les amÃ©liorations\r\nLa vidÃ©o est sans fond sonore (pour l\'obtenir, voir les dÃ©veloppements)\r\nVidÃ©o sans commentaire audio (pour l\'obtenir, voir les dÃ©veloppements)\r\nLa vidÃ©o dure 8 secondes\r\nLe nombre de modifications est d\'un seul aprÃ¨s la soumission de la vidÃ©o, pour plus de modifications, voir les dÃ©veloppements\r\n\r\nRemarque\r\nLa vidÃ©o de n\'importe quel service affichera votre logo seulement 8 secondes pour augmenter la durÃ©e de la vidÃ©o, voir les Ã©volutions\r\n\r\ncertains de mes travaux\r\nhttps://mostaql.com/u/theprince', 'VidÃ©o publicitaire graphique animÃ©e pour votre site Web ou produit, ', 'f477c04157ee91b82a5429264575dbed.jpg', 300, 17, 4, 'Good Seller', '1 Hour', '124'),
	(63, 'Que la paix soit sur vous, je vous propose un service d\'animation graphique pour vos publicitÃ©s, reportages ou autres.\r\nLa taille de la vidÃ©o est de 1080/1920 en qualitÃ© Full HD, ou selon la demande du client\r\n- DurÃ©e du service 3 jours\r\n-Commentaire vocal disponible tous les dialectes, mon commentaire vocal est gratuit\r\nJe peux Ã©crire un script ou un script pour une vidÃ©o\r\n- RÃ©aliser des sons et effets sonores selon la demande du client\r\n-20 ajustements possibles.\r\nL\'utilisation de la langue arabe. anglais franÃ§ais\r\nConception en 5 secondes pour le prix du service\r\n-Format exÃ©cutif pour la vidÃ©o mp4.\r\n\r\nPour plus d\'informations, contactez-nous. Merci', 'Conception vidÃ©o graphique animÃ©e professionnelle', '6d9314686a41710b29ca4e5543423c13.png', 30, 8, 4, 'Good Seller', '1 Hour', '124'),
	(64, 'Remarque importanteÂ : veuillez consulter nos modÃ¨les et nous envoyer un e-mail avant d\'acheter le service.\r\n\r\nPour 5 $ par 5 secondes, nous vous fournirons le meilleur service d\'animation graphique aux meilleurs prix et en un temps record avec des modifications illimitÃ©es\r\nNos vidÃ©os attirent l\'attention du plus grand nombre de tÃ©lÃ©spectateurs possible\r\n\r\nNous vous donnerons :\r\nLa vidÃ©o est en Full HD 1080 de la plus haute qualitÃ©\r\n-effets sonores\r\nPrÃ©parer le texte s\'il n\'est pas disponible pour l\'acheteur\r\nÃ‰galement disponible dans toutes les tailles de mÃ©dias sociaux Instagram - Facebook - Snapchat\r\n\r\n*** Commentaire audio que nous pouvons fournir moyennant des frais supplÃ©mentaires (le coÃ»t de la vidÃ©o n\'inclut pas le commentaire) ***', 'Graphiques animÃ©s professionnels - Haute qualitÃ©', '1670269e76157baa4eb6b6effd4a282f (1).png', 200, 4, 4, 'Good Seller', '1 Hour', '124'),
	(65, 'Pour 5 $, je mettrai un lien texte sponsorisÃ© pour vous pendant une pÃ©riode de 30 jours sur le site Jordan Global Business Directory qui apparaÃ®tra sur toutes les pages du site In Footer.\r\n\r\n* POUR FAIRE SUIVRE LES LIENS, VOUS POUVEZ CHOISIR PARMI LES DÃ‰VELOPPEMENTS DE SERVICE\r\n* Pour une banniÃ¨re publicitaire mesurant 450px * 65px qui s\'affiche sur toutes les pages, vous pouvez choisir parmi les Ã©volutions du service\r\n\r\nPour les nouveaux clients, vous obtenez (un mois supplÃ©mentaire gratuit) une fois lorsque vous demandez un abonnement de 3 mois ou plus\r\n\r\nLe site contient des milliers d\'entreprises enregistrÃ©es et vous obtiendrez donc des backlinks vers votre site avec le nombre d\'entreprises enregistrÃ©es.\r\n* 92% des visiteurs du site Web proviennent du moteur de recherche Google.\r\n* 90% des visiteurs du site viennent de Jordanie et des pays arabes du Golfe.\r\n* Plus de 1500 visites quotidiennes sur le site.\r\n\r\n- Il est exigÃ© que le site soit exempt de ce qui viole la charia, la morale et les bons principes.\r\n- Le service vous aide Ã  gagner la confiance de Google et accÃ©lÃ¨re le classement de votre site dans les moteurs de recherche et son apparition dans les premiers rÃ©sultats de recherche, et ce n\'est pas un service d\'apport de trafic.\r\n\r\nPour consulter le site internet : https://bit.ly/3nRsonb', 'Annonce textuelle Do Follow sur le site Web Jordan Directory', '06f7db9a9ab874ec07f7a9df8f18e64f.png', 60, 3, 6, 'Good Seller', '1 Hour', '124'),
	(66, 'PublicitÃ© Un lien de publicitÃ© textuelle pour votre site (composÃ© de 4 mots de texte) sur la page principale et les deux articles du site Web d\'Al-Mukhtalaf Informatics, l\'un des sites arabes les plus puissants\r\n\r\nLa durÃ©e de l\'annonce restant sur la page en cas de demande du service de base uniquement, sans dÃ©veloppements = un mois\r\n\r\nwww.mo5talf.com\r\n-------\r\nAnalyse de domaine pourÂ :\r\nmo5talf.com\r\nDate : 29 janvier 2022\r\nPageRank Google : 5/10\r\nscore RCPÂ : 5,6/10\r\nAutoritÃ© de domaineÂ : 64\r\nAutoritÃ© de la page : 40\r\nClassement mondialÂ : 139Â 093\r\nAlexa atteint le classementÂ : 125Â 061\r\nNote de spamÂ : 1Â /Â 18\r\nLiens externes externes : 17 236\r\nDomaines rÃ©fÃ©rentsÂ : 103\r\n\r\n== La pÃ©riode de publicitÃ© appropriÃ©e pour vous est dans les dÃ©veloppements ci-dessous ====.', 'PublicitÃ© Un lien d\'annonce textuelle pour votre site (4Â mots textuels)', '0a5a37f99a8a0611303d8990893fa74b.jpg', 500, 4, 6, 'Good Seller', '1 Hour', '124'),
	(67, 'Gagnez du temps\r\nRÃ©duire les coÃ»ts\r\naugmenter les bÃ©nÃ©fices\r\nRÃ©duire les efforts\r\n\r\nVous voulez tout rÃ©aliserÂ ?Â ! Alors vous avez besoin de conseils marketing !\r\n\r\nAvoir des consultants multiplie par 7 le taux de rÃ©ussite des startups\r\n\r\nLes conseils marketing vous font gagner du temps, de l\'argent et des efforts dans la mauvaise direction et vous aident Ã  commencer Ã  travailler de la maniÃ¨re la plus courte et la plus efficace.\r\n\r\nAyman est un spÃ©cialiste du e-marketing, grÃ¢ce Ã  Dieu, j\'ai beaucoup d\'expÃ©rience dans divers aspects du marketing\r\nJ\'ai de l\'expÃ©rience dans la prÃ©paration de plans marketing pour diverses petites, moyennes et grandes entreprises et start-ups\r\nJ\'ai de l\'expÃ©rience dans la production de contenu marketing, de campagnes publicitaires et mÃªme de sites Web, donc la consultation est pratique et exÃ©cutable et vous aide Ã  travailler selon une vision claire et solide.\r\nJe vous expliquerai les Ã©tapes de travail pour dÃ©velopper votre business Ã  travers un message audio via la plateforme Khamsat.Pour rÃ©server une sÃ©ance de consultation via Zoom, vous pouvez visualiser les Ã©volutions du service\r\n\r\nMon profil est sur une plateforme indÃ©pendante avec une note de 5 Ã©toiles de tous les partenaires de rÃ©ussite\r\nhttps://mostaql.com/u/aymanahmed95', 'Conseils marketing avec le chemin le plus court pour atteindre vos objectifs', 'a0dbba17c39ec1de917cceddc3ea350a.png', 50, 6, 6, 'Good Seller', '1 Hour', '124'),
	(68, 'âœ“âœ“Mise Ã  jourâœ“âœ“ : Le 19/09/2021\r\nâ¶ (Avant de rÃ©server le service, veuillez bien lire la description du service et consulter les sites Ã  partir du lien combinÃ© ci-dessous pour comprendre les plans et les dÃ©veloppements)\r\nâ· (La plupart des anciens sites ont Ã©tÃ© modifiÃ©s et remplacÃ©s par de meilleurs sites et seront modifiÃ©s rÃ©guliÃ¨rement pour diversifier le backlink)\r\nâ¸ L\'objectif principal du service estÂ : de crÃ©er le plus grand nombre de backlinks sur le texte annoncÃ© pour aider dans les rÃ©sultats de recherche, et non l\'objectif est d\'envoyer des visites directes depuis les sites\r\n\r\nâ¹ (Information trÃ¨s importanteÂ : le pagerank a Ã©tÃ© annulÃ© de Google il y a des annÃ©es, et le domaine et la Big Authority n\'ont rien Ã  voir avec Google. Ainsi, l\'Ã©lÃ©ment le plus important actuellement dans toute publicitÃ© est les backlinks externes et internes, le trafic et l\'ajustement le rÃ©fÃ©rencement de votre site pour mener Google)\r\n\r\nâº Je mettrai votre annonce de site Web, lien texte, Duflo pour gagner des milliers de backlinks\r\nAmÃ©liorez votre site et attrapez des mots\r\nâ»Service de baseÂ : il s\'agit de 14Â guides\r\nEt dans les dÃ©veloppements, il existe divers sites avec des backlinks de meilleure qualitÃ©\r\nâ¼(Le service est manuel, votre annonce est installÃ©e manuellement)\r\nâ½DurÃ©e : un mois\r\nâ¾âœ“âœ“(Score de spamÂ 0Â %)âœ“âœ“\r\nâ¿ Tous les sites et expliquant les Ã©volutions en dÃ©tail â† : https://bit.ly/2Pdjjpv', 'Annonce d\'un lien texte dans 14 sites de gros rang 6, 5, 4 et 3', '0a639cd2b0ed129c199e3baab63f89a5.jpg', 160, 7, 6, 'Good Seller', '1 Hour', '124'),
	(70, 'Dans ce service, je vous donnerai un backlink dovolo du BBC World Network dans l\'un des articles du site\r\nLe backlink sera une redirection 301 vers votre site\r\n\r\nBacklink Dovolo\r\nDes backlinks permanents\r\n- Il n\'est pas possible de publier le backlink dans un article spÃ©cifique du site\r\nUn seul lien sera placÃ© sur votre site\r\n- La durÃ©e du lien est d\'un mois', 'Backlink Dovolo de bbc.com Guest Post', 'bfea1209d5bd85a47e89ee99be21cf6b.png', 68, 8, 6, 'Good Seller', '1 Hour', '124'),
	(71, 'Si vous recherchez un backlink pour votre site afin d\'amÃ©liorer le classement de votre site dans les rÃ©sultats de recherche et d\'augmenter l\'autoritÃ© de votre page, j\'utilise des liens de type dovolo, car je vous propose un service de publication d\'invitÃ©s pour plusieurs sites qui garantit que\r\nJ\'ai 25 sites Web de force et de prix variÃ©s pour tous les budgets\r\n\r\nJe publierai un article invitÃ© pour vous pendant une semaine, et voici le lien vers les sitesÂ :\r\n\r\nhttps://canadanews24.ca/\r\nhttps://www.analoza.com/\r\nTabibby.com\r\nhttps://www.el7lwa.com\r\nhttps://www.be7awaa.com/?m=1\r\nhttps://beseyat.com/\r\nhttps://faharas.net/\r\nhttps://www.leverus.co.vu/\r\nhttps://www.nafeza2world.com/\r\nhttps://isynapp.com/\r\nhttps://www.yarisaha.com/\r\nhttps://www.irismarvellsolutions.com/\r\nhttps://www.overclockershideou\r\nhttps://www.deficientefisico.com/\r\n9baya.net\r\nhttps://www.elmstba.com/\r\nhttps://www.knoozi.com/\r\nhttps://www.sba7egypt.com/\r\ncoptes-unis.com\r\nhttps://www.3yonnews.com/\r\nalwafd.news\r\nelbashayer.com\r\ngomhuri', 'Publier un article invitÃ© ', '46790ed8bf15d7ecb46a3358268473d2.jpg', 90, 14, 6, 'Good Seller', '1 Hour', '124'),
	(72, 'Je vous propose le service d\'analyse du compte Twitter, d\'analyse de son activitÃ© et de son volume de conversation, et de rÃ©daction d\'un rapport dÃ©taillÃ© sur toutes les donnÃ©es concernant le compte.\r\nLe dÃ©lai est d\'un an Ã  compter de l\'activitÃ© du compte\r\nCe que vous trouvez dans le rapportÂ :\r\nChapitre UnÂ : Le nombre de tweets Ã©mis par le compte, le nombre de likes et de retweets pour ces tweets, le nombre de photos, le nombre de vidÃ©os, le nombre de liens publiÃ©s, le nombre de textes, les hashtags les plus importants que le compte tweetÃ© avec.\r\nChapitre Deux : Les tweets les plus interactifs.\r\nChapitre troisÂ : Les comptes les plus importants qui interagissent avec le compte.\r\nChapitre QuatreÂ : L\'heure la plus active pendant laquelle le compte est actif, le jour le plus actif pendant lequel le compte est actif.\r\nChronologie de l\'activitÃ© du compte L\'heure la plus active du compte Le jour le plus actif du compte .\r\nVous obtenez un rapport PDF ou PowerPoint coordonnÃ© et organisÃ© sur tous ces points.\r\nChaque page contient l\'un des quatre chapitres mentionnÃ©s ci-dessus.\r\nLe rapport vous aide Ã  analyser votre compte ou celui de vos concurrents, en connaissant son activitÃ©, les caractÃ©ristiques du compte et les forces et faiblesses les plus importantes.\r\nLa condition la plus importante est que le compte Ã  analyser doit Ãªtre ouvert et public et non un compte privÃ© fermÃ©.', 'Analyser le compte Twitter et Ã©tudier son activitÃ© gÃ©nÃ©rale sur Twitter', 'b95e867bbf205c93696d274c54195ace.png', 48, 8, 6, 'Good Seller', '1 Hour', '124'),
	(73, 'Accueillir !\r\n\r\nBienvenue sur ma page de services.\r\n\r\nJe me prÃ©sente comme Huda, qui se spÃ©cialise dans le e-marketing avec une grande expÃ©rience et a travaillÃ© avec de nombreuses entreprises locales et saoudiennes. J\'ai de l\'expÃ©rience avec le pixel Facebook, le lien et le suivi des achats et des Ã©vÃ©nements.\r\n\r\nJ\'ai une grande flexibilitÃ© dans le travail, une rapiditÃ© de travail et un prix appropriÃ©, et j\'accepte tous les commentaires et changements de travail.\r\n\r\nJe vais ajuster et installer les pixels pour suivre les comportements des clients et suivre les achats.\r\n\r\nN\'hÃ©sitez pas Ã  me contacter, je recherche un service qui vous plaise\r\n\r\nSalutations', 'Je me prÃ©sente comme Huda, spÃ©cialiste en e-marketing', 'b9745d206e5a4f74c1e2e668c28ba8d5.jpg', 123, 9, 6, 'Good Seller', '1 Hour', '124'),
	(74, 'CrÃ©er une base de donnÃ©es Ã  l\'aide du serveur SQL', 'CrÃ©er une base de donnÃ©es Ã  l\'aide du serveur SQL', 'imagecard3.jpg', 1200, 3, 6, 'Good Seller', '1 Hour', '124'),
	(75, 'CrÃ©er une base de donnÃ©es Ã  l\'aide du serveur SQL', 'CrÃ©er une base de donnÃ©es Ã  l\'aide du serveur SQL', 'imagecard3.jpg', 1235, 3, 4, 'Good Seller', '1 Hour', '124');
/*!40000 ALTER TABLE `products` ENABLE KEYS */;

-- Dumping structure for table project_pfe.users
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Email` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image_user` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT 'image_default.png',
  `role` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT 'user',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table project_pfe.users: ~15 rows (approximately)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `name`, `last_name`, `Email`, `password`, `image_user`, `role`) VALUES
	(3, 'brahim', 'elguabdi', 'brahim2001elguabdi@gmail.com', '123', 'julian-wan-WNoLnJo7tS8-unsplash.jpg', 'user'),
	(4, 'naser', 'farid', 'naser123faride@gmail.com', 'faris 123', 'vince-fleming-_THUISs23CI-unsplash.jpg', 'user'),
	(5, 'admin', 'harakati', 'Azuz123@gmail.com', '123', 'itay-verchik-YmQ8TrsieE4-unsplash.jpg', 'admin'),
	(6, 'mohamed', 'khebabi', 'mohammed@gmail.com', 'mohammed123', 'menuser.jpg', 'user'),
	(7, 'Salah', 'belfirm', 'salah2001@gmail.com', 'salah12', 'janko-ferlic-G-jo31ESuRE-unsplash.jpg', 'user'),
	(8, 'chamae', 'goudali', 'chaimae2001@gmail.com', 'chaimae123', 'vinicius-wiesehofer-BBEbl2WKRlU-unsplash.jpg', 'user'),
	(9, 'omaima', 'Jride ', 'omaima2812@gmail.com', 'jride123', 'girluser.jpg', 'user'),
	(14, 'khalid', 'elguabdi', 'brahim2001elguabdi@gmail.com', '123', 'image_default.png', 'user'),
	(15, 'simo', 'kheb', 'khebari@gmail.com1', '1324242', 'charlie-green-3JmfENcL24M-unsplash.jpg', 'user'),
	(17, 'yahya ', 'elguabi', 'yah@', '123', 'julian-wan-WNoLnJo7tS8-unsplash.jpg', 'user'),
	(18, 'simo', 'khebabi', 'khebai2001elguabdi@gmail.com', '1234', 'image_default.png', 'user'),
	(19, 'naser', 'faride', 'faride2001elguabdi@gmail.com', '1234', 'image_default.png', 'user'),
	(20, 'naser', 'faride', 'faride2001@gmail.com', '1234', 'image_default.png', 'user'),
	(21, 'OUM', '', '', '', 'image_default.png', 'user'),
	(22, 'oumaima', 'AIT SAIS', 'oumaima0048@gmail.com', '123', 'image_default.png', 'user'),
	(23, 'simo', 'khebabi', 'simo2001@gmail.com', '123', 'image_default.png', 'user');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
